amazonProperties:
   endpointUrl: https://s3.us-east-1.amazonaws.com
   accessKey: AKIATHMYRW25AOONQYTX
   secretKey: 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
   bucketName: imgvidco

spring:
  servlet:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tucorreo@unmsm.edu.pe
    password: tuclave
    
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://67.205.143.180/tcs7
    username: modulo4
    password: modulo4

server:
   port: 8080
   
eureka:
  client:
    serviceUrl:
      defaultZone: https://modulo-alumno-eureka.herokuapp.com/eureka #http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8080

banner:
  location: classpath:/example/banner.txt
 
spring.mvc.contentnegotiation.media-types.xlsx : application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

