spring:
  servlet:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tucorreo@unmsm.edu.pe
    password: tuclave
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://67.205.143.180/tcs7
    username: modulo4
    password: modulo4
  jpa:
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
      location: classpath:/example/banner.txt
  mvc:
    contentnegotiation:
      media-types:
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  output:
    ansi:
      enabled: always

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

   
eureka:
  client:
    serviceUrl:
      defaultZone: https://modulo-alumno-eureka.herokuapp.com/eureka #http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    nonSecurePort: 8080

aws:
  services:
    bucket: "imgvidco"

cloud:
  aws:
    stack.auto: false
    region.static: "us-east-1"
    credentials:
      accessKey: "AKIATHMYRW25IH2CX7NZ"
      secretKey: "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"
